version: '3.7'
services:
    web:
        build: .
        command: sh -c "python ./main/manage.py makemigrations core && python ./main/manage.py migrate && python ./main/manage.py runserver 0.0.0.0:8000"
        volumes:
        - .:/main
        ports:
        - 8000:8000
        depends_on:
        - db
    db:
        image: postgres:11
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
        - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:
 