# Generated by Django 3.2.5 on 2021-07-25 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('staff', 'Staff'), ('client', 'Client')], default='client', max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Event_simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('date_posting', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_event', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_simple', to='core.account')),
                ('participants', models.ManyToManyField(to='core.Account')),
            ],
            options={
                'verbose_name': 'Простая заявка',
                'verbose_name_plural': 'Простые заявки',
            },
        ),
        migrations.CreateModel(
            name='Event_detailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('date_posting', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_event', models.DateTimeField()),
                ('client_title', models.CharField(max_length=256)),
                ('client_body', models.TextField()),
                ('client_file', models.FileField(upload_to='files')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_detailed', to='core.account')),
                ('participants', models.ManyToManyField(to='core.Account')),
            ],
            options={
                'verbose_name': 'Расширенная заявка',
                'verbose_name_plural': 'Расширенные заявки',
            },
        ),
    ]
